# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0529be3a563b69e984929b9e292f58e3cd4b4c4b17c566220d50044f8e2710e18cd4f9f56649d0a5e3be6351aee33d9289e4a6efe281acfad93310cd8756e72

test:
  secret_key_base: 3e7bc1223617afec2ee9fd15aa199ef68d6421dde74af6f4740a700642d540e32c85bfcd9127e6f3f6848e30a3b448426a19bfff9a14a1a50b09c046ae0bf693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
